# Generated by Django 2.2 on 2023-07-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='text_answer',
            field=models.TextField(blank=True),
        ),
    ]
